// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARFNvtR-evSYMI7HvytlLKbqlaDpuBW78',
    appId: '1:513167480670:web:b6b27e50939b440ce0e1cf',
    messagingSenderId: '513167480670',
    projectId: 'skillsearch-c085e',
    authDomain: 'skillsearch-c085e.firebaseapp.com',
    storageBucket: 'skillsearch-c085e.appspot.com',
    measurementId: 'G-JCFMQP5HWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAN9LblmYJmWDO7o04nPnkrDoiwLjuNCQ',
    appId: '1:513167480670:android:713c80e7b7b09b21e0e1cf',
    messagingSenderId: '513167480670',
    projectId: 'skillsearch-c085e',
    storageBucket: 'skillsearch-c085e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPm31u7t0kuS6V1M5IGlbOZHiN2bJaBzQ',
    appId: '1:513167480670:ios:6f530350cc48224de0e1cf',
    messagingSenderId: '513167480670',
    projectId: 'skillsearch-c085e',
    storageBucket: 'skillsearch-c085e.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPm31u7t0kuS6V1M5IGlbOZHiN2bJaBzQ',
    appId: '1:513167480670:ios:ab96b9e638177aeee0e1cf',
    messagingSenderId: '513167480670',
    projectId: 'skillsearch-c085e',
    storageBucket: 'skillsearch-c085e.appspot.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
